
The Nautilus DevOps team has started practicing some pods and services deployment on Kubernetes platform as they are planning to migrate most of their applications on Kubernetes platform. Recently one of the team members has been assigned a task to create a pod as per details mentioned below:
1.	Create a pod named pod-httpd using the image httpd with latest tag only and remember to mention tag i.e httpd:latest.
2.	Labels app should be named as httpd_app, also container should be named as httpd-container.
Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.
 
 Solution:
 
# to create a pod run the below, image name , pod name , basic skeleton file will be created.
  kubectl run pod-httpd --image=httpd:latest --dry-run=client -o yaml > /home/thor/pod.yml
 # go to the directory
 cd /home/thor
 # edit the pod.yml and save and quit
   vi pod.yml
 
thor@jump_host ~$ cat pod.yml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: httpd_app
  name: pod-httpd
spec:
  containers:
  - image: httpd:latest
    name: httpd-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
thor@jump_host ~$
 

 
