The Nautilus Application team is planning to deploy one of the php-based application on Kubernetes cluster.
As per discussion with DevOps team they decided to use nginx and phpfpm. Additionally, they shared some custom configuration requirements. 
Below you can find more details. Please complete the task as per requirements mentioned below:


1.) Create a config map nginx-config for nginx.conf as we want to add some custom settings for nginx.conf.

a) Change default port 80 to 8092 in nginx.conf.

b) Change default document root /usr/share/nginx to /var/www/html in nginx.conf.

c) Update directory index to index index.html index.htm index.php in nginx.conf.




b) Create a shared files volume shared-files that will be used by both containers (nginx and phpfpm) also it should be emptyDir: {}

c) Map the ConfigMap we declared above as a volume for the pod. Name the volume as nginx-config-volume

d) Nginx container should be named as nginx-container and it should use nginx:latest image. PhpFPM container should be named as php-fpm-container and it should use php:7.2-fpm image.

e) The shared volume shared-files should be mounted at /var/www/html location in both containers.

f) Add one more volume for nginx-container. Name it as nginx-config-volume, mount path should be /etc/nginx/nginx.conf and subPath should be nginx.conf

Before clicking on finish button always make sure to check if all pods are in running state.

You can use any labels as per your choice.

Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.


Solution:

thor@jump_host ~$ cat ng-con.yml 
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data: 
  nginx.conf: |
   http {
      server {
          listen       8092;
          server_name  localhost;
          location / {
            root   /var/www/html; #Change this line
            index  index.html index.htm index.php;
        }
      }
    }
    
    
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-phpfpm
spec:
  volumes:
    # Create the shared files volume to be used in both pods
  - name: shared-files
    emptyDir: {}
    
    # Add the ConfigMap we declared above as a volume for the pod
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  containers:
  - image: php:7.2-fpm
    name: php-fpm-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
     
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-config-volume
      subPath: nginx.conf
    - mountPath: /var/www/html
      name: shared-files
