There are a number of parameters that are used by applications. We need to define these as environment variables so that we can use them as needed within different configs. 
Below is a scenario which needs to be configured on Kubernetes cluster. 
Please find below more details about it.


Create a namespace named as fieldref-namespace.

Create a pod named envars-fieldref under the namespace fieldref-namespace.

Configure spec as the container name should be fieldref-container, use image busybox preferable latest tag, use command 'sh', '-c' and args should be

'while true; do echo -en '/n'; printenv NODE_NAME POD_NAME POD_NAMESPACE; printenv POD_IP POD_SERVICE_ACCOUNT; sleep 10; done;'

(Note: please take care of indentations)

Define five environment variables as mentioned below:
a.) The first env should be named as NODE_NAME, set valueFrom fieldref and fieldPath should be spec.nodeName.

b.) The second env should be named as POD_NAME, set valueFrom fieldref and fieldPath should be metadata.name.

c.) The third env should be named as POD_NAMESPACE, set valueFrom fieldref and fieldPath should be metadata.namespace.

d.) The fourth env should be named as POD_IP, set valueFrom fieldref and fieldPath should be status.podIP.

e.) The fifth env should be named as POD_SERVICE_ACCOUNT, set valueFrom fieldref and fieldPath shoulbe be spec.serviceAccountName.

Set restart policy to Never.

To check the output, exec the pod and use printenv command.

Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.



Solution :

to create namespace :
 
```kubectl create namespace fieldref-namespace```

to create pod :

```kubectl run envars-fieldref --image=nginx:latest --namespace=fieldref-namespace --dry-run=client -o yaml > /home/thor/pod.yml```

edit the file to add env as below:

thor@jump_host ~$ cat pod.yml 
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: envars-fieldref
  namespace: fieldref-namespace
spec:
  containers:
  - image: nginx:latest
    name: fieldref-container
    command: ['sh', '-c']
    args: 
    - while true; do 
        echo -en '/n'; 
        printenv NODE_NAME POD_NAME POD_NAMESPACE; 
        printenv POD_IP POD_SERVICE_ACCOUNT; 
        sleep 10; 
      done;
    env:
      - name : NODE_NAME
        valueFrom:
           fieldRef:
               fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
           fieldRef:
               fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
           fieldRef:
               fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
           fieldRef:
               fieldPath: status.podIP
      - name: POD_SERVICE_ACCOUNT
        valueFrom: 
           fieldRef:
               fieldPath: spec.serviceAccountName
  restartPolicy: Never

Verify by running :

```kubectl get pods --namespace=fieldref-namespace```
to enter the pod execute:
```kubectl exec -it "envars-fieldref" --namespace=fieldref-namespace /bin/sh```
