Init Containers in Kubernetes:	

There are some applications that need to be deployed on Kubernetes cluster and these apps have some pre-requisites where some configurations need to be changed before deploying the app container. 
Some of these changes cannot be made inside the images so the DevOps team has come up with a solution to use init containers to perform these tasks during deployment. 
Below is a sample scenario that the team is going to test first.

1.Create a Deployment named as ic-deploy-datacenter.

2.Configure spec as replicas should be 1, labels app should be ic-datacenter, template's metadata lables app should be the same ic-datacenter.

3.The initContainers should be named as ic-msg-datacenter, use image fedora, preferably with latest tag and use command '/bin/bash', '-c' and 'echo Init Done - Welcome to xFusionCorp Industries > /ic/beta'. 
The volume mount should be named as ic-volume-datacenter and mount path should be /ic.

4.Main container should be named as ic-main-datacenter, use image fedora, preferably with latest tag and use command '/bin/bash', '-c' and 'while true; do cat /ic/beta; sleep 5; done'. 
The volume mount should be named as ic-volume-datacenter and mount path should be /ic.

5.Volume to be named as ic-volume-datacenter and it should be an emptyDir type.

Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

Tips:Specialized containers that run before app containers in a Pod. Init containers can contain utilities or setup scripts not present in an app image.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ic-datacenter
  name: ic-deploy-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-datacenter
  strategy: {}
  template:
    metadata:
      labels:
        app: ic-datacenter
    spec:
      initContainers:
      - image: fedora:latest
        name: ic-msg-datacenter
        command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/beta']
        volumeMounts: 
        - mountPath: /ic
          name: ic-volume-datacenter
      containers:
      - image: fedora:latest
        name: ic-main-datacenter
        command: ['/bin/bash', '-c', 'while true; do cat /ic/beta; sleep 5; done']
        volumeMounts: 
        - mountPath: /ic
          name: ic-volume-datacenter
      volumes:
      - name: ic-volume-datacenter
        emptyDir: {}
