# The Nautilus DevOps team wants to create a ReplicationController to deploy several pods. 
# They are going to deploy applications on these pods, which need some highly available infrastructure. 
# Below you can find exact details, and please create the ReplicationController accordingly.


# Create a ReplicationController using httpd image, preferably with latest tag, and name it as httpd-replicationcontroller.

# Labels app should be httpd_app, and labels type should be front-end. The container should be named as httpd-container and also make sure replica counts are 3.

# All pods should be running state.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

Solution:


create the below file with kind and apiVersion matching ReplicationController object.

# To maintain specified number of pods it Recommended is to use deployment. otherwise replicaset. 
# ReplicationController is depreceated. 

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: httpd_app
    type: front-end
  name: httpd-replicationcontroller
spec:
  replicas: 3
  selector:
      app: httpd_app
      type: front-end
  template:
    metadata:
      labels:
        app: httpd_app
        type: front-end
    spec:
      containers:
      - image: httpd:latest
        name: httpd-container
        
   # Verification:
    thor@jump_host ~$ kubectl get replicationcontroller
   NAME                          DESIRED   CURRENT   READY   AGE
   httpd-replicationcontroller   3         3         3       4m30s
   
thor@jump_host ~$ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
httpd-replicationcontroller-8vxxp   1/1     Running   0          5m6s
httpd-replicationcontroller-9d28q   1/1     Running   0          5m6s
httpd-replicationcontroller-l2t29   1/1     Running   0          5m6s
        
  The difference between deployment and replicationcontroller yaml is 
  
  Deployment file --
  
  apiVersion: apps/v1
  kind: Deplopyment
  
  ReplicationController File --
  apiVersion: v1
  kind: ReplicationController
  
  Under Selector section, matchLabels is not required for ReplicationController.
  
  selector:
    matchLabels:
      app: httpd_app
      type: front-end
      
  selector:
      app: httpd_app
      type: front-end
      
   Tips: you could use the below command to create yaml file and then modify for speedy deployment
   
   kubectl create deployment httpd-replicationcontroller --image=httpd:latest --replicas=3 --dry-run=client -o yaml > /home/thor/rc.yml
